name: Java CI with Maven + SonarQube

on:
  push:
    branches: [main]
  workflow_dispatch:
permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      

