name: Terraform apply infra

on:
  pull_request_review:
    types: [submitted]

  workflow_dispatch:
permissions:
  contents: read
  id-token: write

env:
  ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
  ROLE_NAME: ${{ secrets.ROLE_NAME }}

jobs:
  build:
    if: github.event.review.state == 'approved' && github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ env.ACCOUNT_ID }}:role/${{ env.ROLE_NAME }}
          aws-region: ap-south-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Plane 
        working-directory: ./infra
        run: |
          terraform init
          terraform plan 

